[package]
name = "evomata12"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
gridsim-ui = "0.2.0"
gridsim = "0.2.0"
nalgebra = "0.14.3"
rand = "0.5.0-pre.2"
noisy_float = "0.1.4"
boolinator = "2.4.0"
array-init = "0.0.3"
